### ISSUE TITLE
Redirecting logged in users

### ISSUE THREAD

**Issue by sevannerse** [manchenkoff/nuxt-auth-sanctum#10]
Hi @manchenkoff,
What do you think about redirecting to `onLogin` instead of giving an error if the user is already authenticated and attempting to log in again?
Thanks in advance.

**Comment by manchenkoff** [comment]
Hey @sevannerse, it depends on what you mean :) I assume there might be 2 different cases:

1. when we have a user state (`isAuthenticated = true`) on the Nuxt side and we throw an error before calling an API
2. when we do not have a user state yet (`isAuthenticated = false`) but the API returns an unsuccessful response because user is logged in already, which by the way might be implemented differently depending on the project (e.g. redirect, 403, 401, etc)

In my opinion, we could redirect to `onLogin` only in 1st scenario since we cannot control the behavior of the API. Still, in general, I would say that it's a bad practice to ignore errors instead of properly checking `isAuthenticated` state before the call.

**Comment by sevannerse** [comment]
Hey @manchenkoff,

I was talking about the first case. As you mentioned in your comment, If we have a user state(`isAuthenticated = true`) on the Nuxt side, it means the Nuxt side is sure a user logged in. Somehow, the user may try to log in again. The package throws an [error](https://github.com/manchenkoff/nuxt-auth-sanctum/blob/ea3453da4cdcebf63e1442f38c493caa418da13c/src/runtime/composables/useSanctumAuth.ts#L41) when the situation occurs for now. 

At that point, my suggestion is to redirect the user to `onLogin` path may be more responsive and fluent. If it fits you too, I would like to open a PR that makes related changes.

**Comment by manchenkoff** [comment]
I would suggest using configurable behavior by introducing a new boolean `redirectIfAuthenticated` option, so if you want to throw an exception, you set it to `false`, otherwise - we check existence of redirect endpoint config and do the redirect w/o any error.

If it sounds good, feel free to raise a PR! @sevannerse

**Comment by manchenkoff** [comment]
Published as v0.0.13
