### ISSUE TITLE
Remote domain problem

### ISSUE THREAD

**Issue by Jonston** [manchenkoff/nuxt-auth-sanctum#121]
Hello. Transferred the API part (laravel) to a remote domain. How can I now configure it to send CSFR_TOKEN cookies to this domain from localhost:3000?

**Comment by manchenkoff** [comment]
Hello @Jonston, unfortunately when you work with cookies, you have to use the same TLD (top level domain). In your case either both applications should be running on localhost or on the same domain, for example Laravel on `api.domain.com` and Nuxt on `domain.com`.

However, you can also use token authentication instead of cookies, check the documentation for more details.

**Comment by Jonston** [comment]
thanks a lot

**Comment by manchenkoff** [comment]
> thanks a lot Sanctum work with subdomain in a same domain? 

Yes, you just need to configure SESSION_DOMAIN and CORS properly on the Laravel side.

> And your package support token auth?

Yes, you can choose which method to use, either `token` or `cookie`.

You can find all the details here - https://manchenkoff.gitbook.io/nuxt-auth-sanctum.

**Comment by manchenkoff** [comment]
I'm closing this for now, feel free to add more questions in case further help is needed
