### ISSUE TITLE
[Question] Not saving the token in the cookie, in token mode ("message":"Unauthenticated.")

### ISSUE THREAD

**Issue by eduardojsc18** [manchenkoff/nuxt-auth-sanctum#149]
Describe the bug
Good morning! I'm having a problem with the option to save my authentication token in a cookie. My back-end returns exactly as it is in the documentation (a simple JSON containing only the token {token: <my_token>}) but it does not save it in the cookie, so, after returning the token, the application tries to connect to the USER but as unauthenticated. BUT if I put the save settings via localstorage in app.config it works perfectly

Expected behavior
I need you to save the token in cookies

Screenshots
![image](https://github.com/user-attachments/assets/27ddef8d-bc4c-4205-b994-e0923e615173)
![image](https://github.com/user-attachments/assets/cb7ef6cf-3f7e-41f0-8086-e503fb3a02d8)

Module information

"nuxt-auth-sanctum": "^0.4.8",
![image](https://github.com/user-attachments/assets/632419ab-6ad1-4182-862b-4b8c16b47354)

Nuxt environment:

"nuxt": "^3.12.4",
Mode: CSR
Environment: local

**Comment by manchenkoff** [comment]
Hey @eduardojsc18, I tried to reproduce the behavior but had no success. I pushed minimal repro for [`breeze-nuxt`](https://github.com/manchenkoff/breeze-nuxt/tree/token-mode) template, could you please try it with your API? 

The branch name is `token-mode`, [here](https://github.com/manchenkoff/breeze-nuxt/compare/token-mode?expand=1) you can find the diff.

On the API side, I have excluded `localhost` from `SANCTUM_STATEFUL_DOMAINS` and used authentication endpoints from `routes/api.php` instead of `routes/web.php`.

**Comment by manchenkoff** [comment]
I'm closing this one due to inactivity, feel free to re-open with further details!
