### ISSUE TITLE
Login Function Returns 401 Error during user Fetch

### ISSUE THREAD

**Issue by mark033100** [manchenkoff/nuxt-auth-sanctum#173]
The module works fine but when I use a dev server to run it through my IP it returns a 401 Error.
The login request was successful and also returns the token but when it go to the user request it returns the 401 error. Although the token was returned the user request didn't include it as header for authorization.

![issue](https://github.com/user-attachments/assets/2a4f89a1-51fa-4b7c-a2ea-a77f2f6dcba7)

**Comment by manchenkoff** [comment]
Hey @mark033100, most of the time the problem lies in the Laravel config. Please, check the documentation and a checklist here - [Nuxt Auth Sanctum / SPA Cookie](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/authentication/spa-cookie). If the issue persists, please re-open it as a bug and provide more details about your environment in the description.

**Comment by mark033100** [comment]
> Hey @mark033100, most of the time the problem lies in the Laravel config. Please, check the documentation and a checklist here - [Nuxt Auth Sanctum / SPA Cookie](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/authentication/spa-cookie). If the issue persists, please re-open it as a bug and provide more details about your environment in the description.

What if I'm using Token as the authentication mode?
Does the same config apply?

**Comment by manchenkoff** [comment]
> What if I'm using Token as the authentication mode?
> Does the same config apply?

Yes, except the part with stateful domain, you can check the docs for Token usage there as well.
