### ISSUE TITLE
feat: implementation of onResponseError

### ISSUE THREAD

**Issue by ibrunotome** [manchenkoff/nuxt-auth-sanctum#2]
Do you plan to implement the `onResponseError` in httpFactory like were in your article? Because in the package the the 422 errors will only show "unprocessable entity" instead of the error details.

If not, is there a way to extends `httpOptions` after the call of `useSanctumClient()`?

**Comment by ibrunotome** [comment]
Overrided this way for now:

```ts
import type { $Fetch } from 'ofetch'
import ApiError from '../models/ApiError'

const UNAUTHENTICATED_STATUSES = new Set([401, 419])
const VALIDATION_ERROR_STATUS = 422

export class ApiServiceBase {
  private readonly client: $Fetch

  constructor(client: $Fetch) {
    this.client = client
  }

  protected get call(): $Fetch {
    return this.client
  }

  protected async handleError({ response }) {
    if (UNAUTHENTICATED_STATUSES.has(response.status)) {
      await navigateTo('/auth/login')

      return
    }

    if (response.status === VALIDATION_ERROR_STATUS) {
      throw new ApiError(response._data)
    }
  }
}
```

And in every method:

```ts
import { ApiServiceBase } from './ApiServiceBase'

export default class ProfileService extends ApiServiceBase {
  async update(name: string, email: string) {
    return await this.call('/api/user', {
      method: 'put',
      body: { name, email },
      onResponseError: (context) => this.handleError(context),
    })
  }

  async updatePicture(file: File) {
    const formData: FormData = new FormData()
    formData.append('profile_picture', file)

    return await this.call('/api/user/profile-picture', {
      headers: {
        'Content-Type': 'multipart/form-data',
      },
      method: 'post',
      body: formData,
      onResponseError: (context) => this.handleError(context),
    })
  }
}
```

You can close the issue if isn't in your plans to put this in the core of the package.

**Comment by manchenkoff** [comment]
Hey @ibrunotome, this is actually was in my initial plan, but there is a problem with that since there is no way to extend $Fetch object after it was created, only passing as an argument like you mentioned in your solution. 
I think that creating common logic for error handling might be not that flexible since redirect and error extraction may be used in higher levels of the application or is not necessary at all.

Another option - catch only calls you want (for example form submissions) with try-catch and do something like this

```typescript
if (error instanceof FetchError) {
        if (error.response === undefined) {
            return error as Error;
        }

        const status = error.response.status;

        if (status === 422) {
            return new ApiValidationError(error.response._data);
        }

        if (status === 429) {
            return createError({
                statusCode: 429,
                message: 'Too many requests, try again later',
            });
        }
    }
```

You can encapsulate this logic into some function like `handleFormError` or so.

**Comment by manchenkoff** [comment]
So, bad news 😄 I checked my theory but it looks like there is no way to set up callbacks (especially async ones) directly in `nuxt.config.ts` because I always get empty objects instead, so we should probably stick to occasional error handling.

I'm closing this issue until I find something else to help with error-handling customization.
