### ISSUE TITLE
How is the token/session expiration being handle?

### ISSUE THREAD

**Issue by ryscript** [manchenkoff/nuxt-auth-sanctum#21]
I've noticed that the session expiration is only an hour, I'd like to increase it to a week or month, after setting it in /config/sanctum.php in my BE, it is still the same.

My question is, is the expiration handled by the module or from BE?

Thanks

**Comment by shayr1** [comment]
@ryscript Make sure your `.env` file has correct session time on the **Laravel** side. For me inside I have `SESSION_LIFETIME=43200` (43200 minutes are one month) and on the cookies in browser the expiry is one month.

That should do it unless you changed other settings much.

**Comment by manchenkoff** [comment]
Hey @ryscript, yes, @shayr1 is right, you can adjust your session lifetime in `.env` or `config/session.php` files. This module will automatically redirect you to the login endpoint if the previous session is not valid anymore (it's done in the middleware layer). Since we do not use any token-based authentication, there is no way to refresh it, but you can leverage [remember me](https://laravel.com/docs/10.x/authentication#remembering-users) feature of Laravel.

**Comment by ryscript** [comment]
All good now guys, Thanks @manchenkoff and @shayr1, I updated the token value instead of the session one, my bad, Thanks again.
