### ISSUE TITLE
[Feature] Set expires or maxAge of the cookie for token storage

### ISSUE THREAD

**Issue by svossen** [manchenkoff/nuxt-auth-sanctum#253]
By default the cookie to store the token doesn’t have `expires` or `maxAge`, so it [becomes a session cookie](https://nuxt.com/docs/api/composables/use-cookie#options). We make use of Laravel [remember](https://laravel.com/docs/11.x/authentication#remembering-users), so the user has the option to stay logged in. Although since the token is stored in a session cookie, this means that when a user closes the browser the cookie is removed and the user has to login again. 

It would be great to have a configuration option to set `expires` or `maxAge` for the token storage cookie.

As a workaround I’m using a custom token storage which is a copy of the nuxt-auth-sancum `cookieTokenStorage`, but with a `maxAge`.

**Comment by manchenkoff** [comment]
Hey @svossen, thanks for bringing this up! 

Unfortunately, token storage is not a part of the module and it is a kind of detached functionality provided just as the default version, so there is no configuration for that since it is not generic. Cookie token storage is just an example of how it can work, but the configuration of your own storage should be handled separately.

In general, token usage is not recommended for authentication in SPA due to security concerns so the proper way would be actually what you did with your own configuration.

If you have any idea on configuration that might be reused across storages besides one cookie-specific implementation, I would be happy to discuss! 👍

**Comment by svossen** [comment]
Thanks for pointing that out! I will look into the security concerns and discuss it with my team.

I’ve got no further ideas right now.
