### ISSUE TITLE
[Feature] Support 'globalAppMiddleware' and 'allow404WithoutAuth'

### ISSUE THREAD

**Issue by ErfanBahramali** [manchenkoff/nuxt-auth-sanctum#3]
support `globalAppMiddleware` and `allow404WithoutAuth` like [nuxt-auth](https://github.com/sidebase/nuxt-auth/ ) library

read about it on:
https://sidebase.io/nuxt-auth/configuration/nuxt-config

```
// Whether to add a global authentication middleware that will protect all pages without exclusion
globalAppMiddleware: false
```
```
// Whether to allow access to 404 pages without authentication. Set this to `false` to force users to sign-in before seeing `404` pages. Setting this to false may lead to vue-router problems (as the target page does not exist)
allow404WithoutAuth: true
```

**Comment by manchenkoff** [comment]
Hey @ErfanBahramali, to be honest, I have some concerns about this functionality of nuxt-auth module in the first place:

1. If we apply global middleware on the module side, we also need to exclude login endpoints (pages) but in some applications, it could be a different page based on the business logic (customer, vendor, manager, etc), so usually it adds more complexity to the application instead of usability. Also, it will decrease the flexibility and simplicity of the module.
2. By default, error pages should be accessible always w/o authentication unless it's an admin back office or so, but if you have some specific content for the authenticated users on this page, then you can easily implement it in the page itself by leveraging `isAuthenticated` computed value (including the redirect to the login page). I am not sure that the authentication module is responsible for the content the user sees on error occurrence.

So, in my opinion, this module should provide some functionality for the authentication w/o changing the application behavior, especially when all these things are unique from one website to another. Feel free to add your thoughts on top of that 🤔

**Comment by ErfanBahramali** [comment]
> Hey @ErfanBahramali, to be honest, I have some concerns about this functionality of nuxt-auth module in the first place:
> 
> 1. If we apply global middleware on the module side, we also need to exclude login endpoints (pages) but in some applications, it could be a different page based on the business logic (customer, vendor, manager, etc), so usually it adds more complexity to the application instead of usability. Also, it will decrease the flexibility and simplicity of the module.
> 2. By default, error pages should be accessible always w/o authentication unless it's an admin back office or so, but if you have some specific content for the authenticated users on this page, then you can easily implement it in the page itself by leveraging `isAuthenticated` computed value (including the redirect to the login page). I am not sure that the authentication module is responsible for the content the user sees on error occurrence.
> 
> So, in my opinion, this module should provide some functionality for the authentication w/o changing the application behavior, especially when all these things are unique from one website to another. Feel free to add your thoughts on top of that 🤔

The default mode remains the same
These can be added as features and enabled in configuration if desired
And it's also true that these things can be implemented without these features, but it would be easier if they were there.

**Comment by manchenkoff** [comment]
I'll see what I can do 👍

**Comment by manchenkoff** [comment]
Hey @ErfanBahramali, I've just released this feature, feel free to test it!

Version of the package - v0.2.0
Docs can be found here - [Nuxt Auth Sanctum](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/v/v0.2.0/usage/middleware/global-middleware)
