### ISSUE TITLE
After updating to v0.1.2: Component is already mounted, please use $fetch instead

### ISSUE THREAD

**Issue by ahoiroman** [manchenkoff/nuxt-auth-sanctum#30]
After updating to 0.1.2, I am getting this warning in the console.log:

> [nuxt] [useAsyncData] Component is already mounted, please use $fetch instead. See https://nuxt.com/docs/getting-started/data-fetching

```
const {status, execute} = await useAsyncData('store', () => client(`/project`, {
    method: 'POST',
    body: state,
  } as FetchOptions)
    .then(() => emit('submit'))
    .catch((error) => form.value.setErrors(formatErrors(error.response._data.errors))),
  {immediate: false}
)
```

**Comment by manchenkoff** [comment]
Hey @ahoiroman, thanks for opening, I'll take a look

**Comment by manchenkoff** [comment]
@ahoiroman 
Can you tell me what version of Nuxt you use?

**Comment by manchenkoff** [comment]
@ahoiroman 
I think I found the problem, I've checked their [source code](https://github.com/nuxt/nuxt/blob/main/packages/nuxt/src/app/composables/asyncData.ts#L341) ad it looks like composables like `useFetch` and `useAsyncData` from now on should be defined only in `setup` scope of the component.

So, I've checked the [latest docs](https://nuxt.com/docs/getting-started/data-fetching#client-only-fetching) and found this:
```
The useFetch composable is meant to be invoked in setup method or called directly at the 
top level of a function in lifecycle hooks, otherwise you should use $fetch method.
```

And I tested your example in several different ways, you can check the code below

```typescript
<script lang="ts" setup>
const { isAuthenticated, user, refreshIdentity } = useSanctumAuth();

const { execute } = await useAsyncData('user', () => refreshIdentity(), {
    immediate: false,
});

function refreshFromGlobalScope() {
    // Does not trigger warning and works well
    execute();
    console.log('refreshed from global scope');
}

async function refreshFromLocalScope() {
    // Triggers warning and still works
    await useAsyncData('user', () => refreshIdentity(), {
        immediate: false,
    });
    console.log('refreshed from local scope');
}

async function refreshWithoutComposables() {
    // Triggers warning and still works
    await refreshIdentity();
    console.log('refreshed without using composables');
}

onMounted(async () => {
    // also works well even with local scope
    await refreshFromLocalScope();
    console.log('refreshed on mount');
});
</script>

<template>
    <p>Your authentication status - {{ isAuthenticated }}</p>
    <p>Identity object - {{ user }}</p>
    <div>
        <button @click="refreshFromGlobalScope">Refetch user (Global)</button>
        <button @click="refreshFromLocalScope">Refetch user (Local)</button>
        <button @click="refreshWithoutComposables">
            Refetch user (Native)
        </button>
    </div>
</template>
```

It looks like that if you want to keep using benefits of `useAsyncData` like data, pending, refresh, etc - then you have to declare it in the `setup`-scope or call it from `onMounted` handler, otherwise you will be able to call it only directly like in the `refreshWithoutComposables` method.

Hope it'll help! 😄

**Comment by ahoiroman** [comment]
Hi,

alright, I can confirm, that I am not able to use useAsyncData inside functions that "live" in `<script setup>`. I wonder why this did not happen on other occasions where useAsyncData is used (without your `client()` composable), but rewriting it to use await `client()...` works fine.

Thanks and sorry for causing you work.
