### ISSUE TITLE
Succesful logged in but api/user return error

### ISSUE THREAD

**Issue by haskadavid** [manchenkoff/nuxt-auth-sanctum#52]
I succefuly logged, i get bearer token and everything OK, but then api/user return error with max_allowed_stack_size There is a loop in Laravel\\Sanctum\\Guard in this function "$user = $this->auth->guard($guard)->user()" ... its call user() function in Illuminate/Auth/RequestGuard and then again it call Laravel\\Sanctum\\Guard. Can you help me please what is wrong?

`{
    "message": "Maximum call stack size of 8339456 bytes (zend.max_allowed_stack_size - zend.reserved_stack_size) reached. Infinite recursion?",
    "exception": "Error",
    "file": "/var/www/html/vendor/laravel/sanctum/src/Guard.php",
    "line": 54,
    "trace": [
        {
            "function": "__invoke",
            "class": "Laravel\\Sanctum\\Guard",
            "type": "->"
        }`

**Comment by manchenkoff** [comment]
Hey @haskadavid, as far I see in the error message, it is related to the Laravel application and not to the package. I would suggest debugging API to find a reason of infinite recursion because I am not that familiar with Laravel source code.

Also, I would like to highlight that the current version of `nuxt-auth-sanctum` does not work wit Bearer token and supports only cookie-based authentication.

**Comment by manchenkoff** [comment]
closing this one since relevant to the backend
