### ISSUE TITLE
[Help Needed] Unable to load user identity

### ISSUE THREAD

**Issue by norjamille-kasan** [manchenkoff/nuxt-auth-sanctum#67]
Unable to load user identity [GET] "http://localhost:8000/api/user": fetch failed

I have the same issue on https://github.com/manchenkoff/nuxt-auth-sanctum/issues/57
except I'm not using docker. I'm just running my laravel (v11) app on http://localhost:8000/ and my nuxt app at http://localhost:3000/

I already did some of the fixes that was said https://github.com/manchenkoff/nuxt-auth-sanctum/issues/57 but the error in the console is still showing.

I really need some help :(. thanks a lot

APP_URL=http://locahost:8000/
SESSION_DOMAIN=localhost
SANCTUM_STATEFUL_DOMAINS=localhost:3000
FRONTEND_URL=http://localhost:3000/

` devServer: { host: "localhost", }, runtimeConfig: { public: { sanctum: { origin: "http://localhost:3000", }, }, }, sanctum: { baseUrl: "http://localhost:8000",  origin: "http://localhost:3000", endpoints: { csrf: "/sanctum/csrf-cookie",  login: "/api/login", logout: "/api/logout",  user: "/api/user", }, redirect: { keepRequestedRoute: true, onLogin: "/", onLogout: "/", onAuthOnly: "/sign-in", onGuestOnly: "/", }, },`

**Comment by manchenkoff** [comment]
Hey @norjamille-kasan, have you tried to remove `SESSION_DOMAIN` config? it doesn't work with localhost properly. If the issue is still applicable, please use this template to provide more details to investigate

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

1. Go to '...'
2. Click on '....'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Module information**

-   Version: [e.g. 0.1.2]
-   Complete configuration of `sanctum` from your `nuxt.config.ts`

```typescript
export default defineNuxtConfig({
    modules: ['nuxt-auth-sanctum'],

    sanctum: {
        baseUrl: 'http://localhost:80',
    },
});
```

**Nuxt environment:**

-   Version: [e.g. 3.11.0]
-   Mode: [e.g. CSR, SSR]
-   Environment: [e.g. local, production]

**Laravel environment:**

-   Version: [e.g. 11.0.0]
-   Sanctum installed via Breeze: [ ]
-   [Checklist](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/other/laravel-api) completed: [ ]

**Additional context**
Add any other context about the problem here. For instance, you can attach the details about the request/response of the application or logs from the backend to make this problem easier to understand.

**Comment by norjamille-kasan** [comment]
@manchenkoff  i solve my problem thanks.
sorry it is my first time submitting github issue :), i really like your module btw that's why i really wanna solve my problem.

Using localhost, i solve it by running `php artisan serve --host localhost` instead of `php artisan serve`
and changing the APP_URL on my laravel app to `http://localhost:8000`. and my Nuxt App running on   `http://localhost:3000`
in this way the console warning is not showing anymore.

**Comment by manchenkoff** [comment]
Hey @norjamille-kasan, no worries! I'm glad you solved your issue 👍  I assume you use Windows, right? Just out of curiosity, which host was set before you changed it to `localhost` in `php artisan serve` command? It might be useful for future investigations

**Comment by norjamille-kasan** [comment]
Yes, I'm using windows. So everytime i run `php artisan server` it says `Server running on [http://127.0.0.1:8000].` :)

**Comment by manchenkoff** [comment]
Thanks for the details @norjamille-kasan 👍

**Comment by jerryklimcik** [comment]
Hi, I am also stuck on this and it takes a lot of experimenting to get it to work. Except I'm on MacOS. I can confirm that `php artisan serve --host localhost` instead of `php artisan serve` solved the problem 🤷 Maybe it'd be worth to mention this, also that for Sail you're using port :80 but locally it's :8000 (something like notes section in the Breeze API readme)

**Comment by manchenkoff** [comment]
@jerryklimcik unfortunately, there are too many options that can be used for the setup, like:
- Nuxt in Docker + Sail
- Nuxt in Docker + artisan serve
- Nuxt local + Sail
- Nuxt local + artisan serve
- Nuxt on node + FPM in production
- Kuber for both in production
- and so on

All these combinations require different setups, so it is the developer's responsibility to adjust them correspondingly. 

> It might be worth mentioning that for Sail you're using port :80, but locally it's :8000 (something like the notes section in the Breeze API readme).

It is not necessarily true for everyone since it depends on the `docker-compose.yml` file with the Sail containers definition, sometimes people use 80:80 ports and sometimes 8000:8000.
